### ISSUE TITLE
license

### ISSUE THREAD

**Issue by Coppelia** [stepjam/v_repExtOpenGL3Renderer#1]
Hi Stephen, can you please adjust the license text?
Cheers

**Comment by stepjam** [comment]
Hi Marc. Sure, what license is appropriate for a V-REP plugin?

**Comment by Coppelia** [comment]
any - V-REP plugins do not have any restrictions on their type of license. Very permissive licenses are of course preferred. Actually most of our plugins are licensed under BSD V2

**Comment by stepjam** [comment]
Ok, great. Anyway, would be nice to have this explicitely mentioned somewhere.
